<<<<<<< HEAD
spring.application.name=ProyectoFinal4BIM
=======
spring.application.name=ProyectoFinalBIM4
>>>>>>> b6ad4508308d3b105d6b189e9babf7642e9105a0
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/DB_ahorcado?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=quintom
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true